//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:19:13 PM CEST 
//


package korenski.soap.fakture_model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Faktura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Faktura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID_poruke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Dobavljac" type="{http://korenski/soap/fakture_model}TFirma"/>
 *         &lt;element name="Kupac" type="{http://korenski/soap/fakture_model}TFirma"/>
 *         &lt;element name="Datum_fakture" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Broj_fakture">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Datum_valute" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Oznaka_valute">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *               &lt;pattern value="[A-Z]{3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vrednost_robe">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vrednost_usluga">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ukupno_roba_I_usluge">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ukupan_rabat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ukupan_porez">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Iznos_za_uplatu">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Uplata_na_racun" type="{http://korenski/soap/fakture_model}TBroj_racuna"/>
 *         &lt;element name="Stavke">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://korenski/soap/fakture_model}Stavka_fakture" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Faktura", propOrder = {
    "idPoruke",
    "dobavljac",
    "kupac",
    "datumFakture",
    "brojFakture",
    "datumValute",
    "oznakaValute",
    "vrednostRobe",
    "vrednostUsluga",
    "ukupnoRobaIUsluge",
    "ukupanRabat",
    "ukupanPorez",
    "iznosZaUplatu",
    "uplataNaRacun",
    "stavke"
})
@Entity
public class Faktura {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long id;

    @XmlElement(name = "ID_poruke", required = true)
    protected String idPoruke;
    @XmlElement(name = "Dobavljac", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected TFirma dobavljac;
    @XmlElement(name = "Kupac", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected TFirma kupac;
    @XmlElement(name = "Datum_fakture", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date datumFakture;
    @XmlElement(name = "Broj_fakture", required = true)
    protected String brojFakture;
    @XmlElement(name = "Datum_valute", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date datumValute;
    @XmlElement(name = "Oznaka_valute", required = true)
    protected String oznakaValute;
    @XmlElement(name = "Vrednost_robe", required = true)
    protected BigDecimal vrednostRobe;
    @XmlElement(name = "Vrednost_usluga", required = true)
    protected BigDecimal vrednostUsluga;
    @XmlElement(name = "Ukupno_roba_I_usluge", required = true)
    protected BigDecimal ukupnoRobaIUsluge;
    @XmlElement(name = "Ukupan_rabat", required = true)
    protected BigDecimal ukupanRabat;
    @XmlElement(name = "Ukupan_porez", required = true)
    protected BigDecimal ukupanPorez;
    @XmlElement(name = "Iznos_za_uplatu", required = true)
    protected BigDecimal iznosZaUplatu;
    @XmlElement(name = "Uplata_na_racun", required = true)
    protected String uplataNaRacun;
    @XmlElement(name = "Stavke", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected Faktura.Stavke stavke;
    @XmlTransient
    protected boolean tip;
    @XmlTransient
    protected boolean zatvorena;
    

    
    public Faktura() {
		super();
		this.zatvorena=false;
		// TODO Auto-generated constructor stub
	}

	/**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDPoruke(String value) {
        this.idPoruke = value;
    }

    /**
     * Gets the value of the dobavljac property.
     * 
     * @return
     *     possible object is
     *     {@link TFirma }
     *     
     */
    public TFirma getDobavljac() {
        return dobavljac;
    }

    /**
     * Sets the value of the dobavljac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFirma }
     *     
     */
    public void setDobavljac(TFirma value) {
        this.dobavljac = value;
    }

    /**
     * Gets the value of the kupac property.
     * 
     * @return
     *     possible object is
     *     {@link TFirma }
     *     
     */
    public TFirma getKupac() {
        return kupac;
    }

    /**
     * Sets the value of the kupac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFirma }
     *     
     */
    public void setKupac(TFirma value) {
        this.kupac = value;
    }

    
    
    /**
     * Gets the value of the datumFakture property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
//    public XMLGregorianCalendar getDatumFakture() {
//        return datumFakture;
//    }
//
//    /**
//     * Sets the value of the datumFakture property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *     
//     */
//    public void setDatumFakture(XMLGregorianCalendar value) {
//        this.datumFakture = value;
//    }

    public Long getId() {
		return id;
	}
   
	public void setId(Long id) {
		this.id = id;
	}
    
	public boolean isTip() {
		return tip;
	}

	public void setTip(boolean tip) {
		this.tip = tip;
	}

	public boolean isZatvorena() {
		return zatvorena;
	}

	public void setZatvorena(boolean zatvorena) {
		this.zatvorena = zatvorena;
	}

	public String getIdPoruke() {
		return idPoruke;
	}

	public void setIdPoruke(String idPoruke) {
		this.idPoruke = idPoruke;
	}

	public Date getDatumFakture() {
		return datumFakture;
	}

	public void setDatumFakture(Date datumFakture) {
		this.datumFakture = datumFakture;
	}

	public Date getDatumValute() {
		return datumValute;
	}

	public void setDatumValute(Date datumValute) {
		this.datumValute = datumValute;
	}

	/**
     * Gets the value of the brojFakture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojFakture() {
        return brojFakture;
    }

    /**
     * Sets the value of the brojFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojFakture(String value) {
        this.brojFakture = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
//    public XMLGregorianCalendar getDatumValute() {
//        return datumValute;
//    }
//
//    /**
//     * Sets the value of the datumValute property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link XMLGregorianCalendar }
//     *     
//     */
//    public void setDatumValute(XMLGregorianCalendar value) {
//        this.datumValute = value;
//    }

    /**
     * Gets the value of the oznakaValute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznakaValute() {
        return oznakaValute;
    }

    /**
     * Sets the value of the oznakaValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznakaValute(String value) {
        this.oznakaValute = value;
    }

    /**
     * Gets the value of the vrednostRobe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostRobe() {
        return vrednostRobe;
    }

    /**
     * Sets the value of the vrednostRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostRobe(BigDecimal value) {
        this.vrednostRobe = value;
    }

    /**
     * Gets the value of the vrednostUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostUsluga() {
        return vrednostUsluga;
    }

    /**
     * Sets the value of the vrednostUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostUsluga(BigDecimal value) {
        this.vrednostUsluga = value;
    }

    /**
     * Gets the value of the ukupnoRobaIUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupnoRobaIUsluge() {
        return ukupnoRobaIUsluge;
    }

    /**
     * Sets the value of the ukupnoRobaIUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupnoRobaIUsluge(BigDecimal value) {
        this.ukupnoRobaIUsluge = value;
    }

    /**
     * Gets the value of the ukupanRabat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanRabat() {
        return ukupanRabat;
    }

    /**
     * Sets the value of the ukupanRabat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanRabat(BigDecimal value) {
        this.ukupanRabat = value;
    }

    /**
     * Gets the value of the ukupanPorez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanPorez() {
        return ukupanPorez;
    }

    /**
     * Sets the value of the ukupanPorez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanPorez(BigDecimal value) {
        this.ukupanPorez = value;
    }

    /**
     * Gets the value of the iznosZaUplatu property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznosZaUplatu() {
        return iznosZaUplatu;
    }

    /**
     * Sets the value of the iznosZaUplatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznosZaUplatu(BigDecimal value) {
        this.iznosZaUplatu = value;
    }

    /**
     * Gets the value of the uplataNaRacun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUplataNaRacun() {
        return uplataNaRacun;
    }

    /**
     * Sets the value of the uplataNaRacun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUplataNaRacun(String value) {
        this.uplataNaRacun = value;
    }

    /**
     * Gets the value of the stavke property.
     * 
     * @return
     *     possible object is
     *     {@link Faktura.Stavke }
     *     
     */
    public Faktura.Stavke getStavke() {
        return stavke;
    }

    /**
     * Sets the value of the stavke property.
     * 
     * @param value
     *     allowed object is
     *     {@link Faktura.Stavke }
     *     
     */
    public void setStavke(Faktura.Stavke value) {
        this.stavke = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://korenski/soap/fakture_model}Stavka_fakture" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stavkaFakture"
    })
    @Entity
    
    public static class Stavke {

    	@Id
    	@GeneratedValue(strategy = GenerationType.IDENTITY)
    	@Column(name = "id")
    	private Long id;
    	
        @XmlElement(name = "Stavka_fakture", required = true)
        @OneToMany(cascade = CascadeType.ALL)
        protected List<StavkaFakture> stavkaFakture;

        /**
         * Gets the value of the stavkaFakture property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stavkaFakture property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStavkaFakture().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StavkaFakture }
         * 
         * 
         */
        public List<StavkaFakture> getStavkaFakture() {
            if (stavkaFakture == null) {
                stavkaFakture = new ArrayList<StavkaFakture>();
            }
            return this.stavkaFakture;
        }

    }

}
